services:
  - type: web
    name: mediaconverter
    env: node
    buildCommand: apt-get update && apt-get install -y python3 python3-pip ffmpeg curl && pip install -U yt-dlp && pip install -r python/requirements.txt && mkdir -p python/downloads && npm install && npm run install-server && npm run install-client && cd frontend && npm run build && ls -la dist && python3 -c "import sys; print(sys.path); import yt_dlp; print('yt-dlp version:', yt_dlp.version.__version__)"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_PATH
        value: python3
      - key: PYTHONPATH
        value: /opt/render/project/src
    buildFilter:
      paths:
        - package.json
        - server/**
        - frontend/**
        - python/**
    disk:
      name: media
      mountPath: /opt/render/project/src/python/downloads
      sizeGB: 10
    autoDeploy: false

databases:
  - name: mediaconverter-db
    plan: free
    databaseName: mediaconverter
    ipAllowList: []