services:
  - type: web
    name: mediaconverter
    env: node
    buildCommand: apt-get update && apt-get install -y python3 python3-pip ffmpeg && pip install -r python/requirements.txt && mkdir -p python/downloads && npm install && npm run install-server && npm run install-client && npm run build && ls -la frontend/build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_PATH
        value: python3
    buildFilter:
      paths:
        - package.json
        - server/**
        - frontend/**
        - python/**
    disk:
      name: media
      mountPath: /opt/render/project/src/python/downloads
      sizeGB: 10
    autoDeploy: false

databases:
  - name: mediaconverter-db
    plan: free
    databaseName: mediaconverter
    ipAllowList: []